### ISSUE TITLE
request to add market.geojson to side-by-side map

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-ardmore-road-wh#1]
@ilyankou - Would you please help me to modify this specific version of your side-by-side map design? I uploaded a file (market.geojson) and I would like it to appear as a blue polygon with pop-up opened to display its "name" property (Kingswood Market, 1924-2007) in all versions of the map (1917, 1923, present). Thanks!

**Comment by ilyankou** [comment]
See pull request #2. If you want popups open by default, add `.openPopup();`. For example:

```javascript
L.geoJSON(mkt, {style: style})
  .addTo(map1)
  .bindPopup(mktPopupText)
  .openPopup();
```
